longhorn/charts

charts/longhorn/Chart.yaml
charts/longhorn/questions.yml
charts/longhorn/templates/daemonset-sa.yaml
charts/longhorn/templates/deployment-driver.yaml
charts/longhorn/templates/deployment-ui.yaml
charts/longhorn/templates/postupgrade-job.yaml
charts/longhorn/templates/psp.yaml
charts/longhorn/templates/storageclass.yaml
charts/longhorn/templates/uninstall-job.yaml
charts/longhorn/values.yaml

Signed-off-by: Sheng Yang <sheng.yang@rancher.com>

Longhorn v1.0.2

---

charts/longhorn/Chart.yaml
charts/longhorn/README.md
charts/longhorn/questions.yml
charts/longhorn/templates/clusterrole.yaml
charts/longhorn/templates/crds.yaml
charts/longhorn/templates/daemonset-sa.yaml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/templates/deployment-driver.yaml
charts/longhorn/templates/deployment-ui.yaml
charts/longhorn/templates/ingress.yaml
charts/longhorn/templates/postupgrade-job.yaml
charts/longhorn/templates/uninstall-job.yaml
charts/longhorn/values.yaml

Update version to v1.1.1

---

charts/longhorn/Chart.yaml
charts/longhorn/README.md
charts/longhorn/questions.yml
charts/longhorn/templates/tls-secrets.yaml
charts/longhorn/values.yaml

**DON'T MERGE UNTIL RELEASE**
cc @khushboo-rancher @meldafrawi @kaxing

Update to v1.1.2

---

charts/longhorn/questions.yml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/values.yaml

1. guaranteedEngineCPU
2. volumeAttachmentRecoveryPolicy

Remove deprecated settings

---

charts/longhorn/questions.yml

keep sync with https://github.com/longhorn/longhorn/pull/2792

Update default tag for instance manager in question.yml

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yml
charts/longhorn/templates/clusterrole.yaml
charts/longhorn/templates/crds.yaml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/templates/deployment-ui.yaml
charts/longhorn/templates/storageclass.yaml
charts/longhorn/values.yaml

Update to v1.2.0-rc1

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yml
charts/longhorn/templates/clusterrole.yaml
charts/longhorn/templates/crds.yaml
charts/longhorn/values.yaml

Update to v1.2.0-rc2

---

charts/longhorn/questions.yml
charts/longhorn/values.yaml

Update 1.2.0 rc2 fix

---

charts/longhorn/Chart.yaml
charts/longhorn/README.md
charts/longhorn/questions.yml
charts/longhorn/templates/clusterrole.yaml
charts/longhorn/templates/crds.yaml
charts/longhorn/templates/daemonset-sa.yaml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/templates/deployment-ui.yaml
charts/longhorn/templates/ingress.yaml
charts/longhorn/templates/storageclass.yaml
charts/longhorn/values.yaml

Release v1.2.0

---

charts/longhorn/Chart.yaml

Update chart kubeverion consistent with longhorn-manager repo

---

charts/longhorn/templates/storageclass.yaml
charts/longhorn/values.yaml

https://github.com/longhorn/longhorn/issues/2964

Add default fstype in values.yaml and sc

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/templates/deployment-ui.yaml
charts/longhorn/templates/storageclass.yaml
charts/longhorn/values.yaml

Update to 1.2.1-rc2

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yml
charts/longhorn/values.yaml

Release longhorn v1.2.1 - staging

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/templates/deployment-ui.yaml
charts/longhorn/values.yaml

Release 1.2.1

---

charts/longhorn/questions.yml
charts/longhorn/templates/services.yaml

Add headless services for instance manager pods

---

.github/workflows/release-ondemand.yml

Add release on-demand pipeline

---

.github/workflows/release-ondemand.yml

Add input for on demand pipeline

---

.github/workflows/release-ondemand.yml

Clone from a specific branch

---

.github/workflows/release-ondemand.yml
.github/workflows/release.yml

Add chart-release-action in on-demand pipeline

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yml
charts/longhorn/templates/services.yaml
charts/longhorn/values.yaml

Release 1.2.3

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yml
charts/longhorn/templates/deployment-ui.yaml
charts/longhorn/templates/services.yaml
charts/longhorn/values.yaml

Release 1.2.4-rc1

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yml
charts/longhorn/values.yaml

Release 1.2.4

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/templates/clusterrole.yaml
charts/longhorn/templates/crds.yaml
charts/longhorn/templates/daemonset-sa.yaml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/templates/deployment-ui.yaml
charts/longhorn/templates/deployment-webhook.yaml
charts/longhorn/templates/registry-secret.yaml
charts/longhorn/templates/serviceaccount.yaml
charts/longhorn/templates/services.yaml
charts/longhorn/templates/storageclass.yaml
charts/longhorn/values.yaml

Release 1.3.0-rc1

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/templates/crds.yaml
charts/longhorn/templates/daemonset-sa.yaml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/templates/deployment-driver.yaml
charts/longhorn/templates/deployment-ui.yaml
charts/longhorn/templates/deployment-webhook.yaml
charts/longhorn/templates/postupgrade-job.yaml
charts/longhorn/templates/uninstall-job.yaml
charts/longhorn/values.yaml

Release 1.3.0-rc2

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/values.yaml

Release 1.3.0 rc3

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/templates/crds.yaml
charts/longhorn/values.yaml

Release 1.3.0

---

charts/longhorn/questions.yaml

v1.3.0 questions update

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/templates/crds.yaml
charts/longhorn/templates/daemonset-sa.yaml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/templates/deployment-driver.yaml
charts/longhorn/templates/deployment-ui.yaml
charts/longhorn/templates/deployment-webhook.yaml
charts/longhorn/templates/ingress.yaml
charts/longhorn/templates/postupgrade-job.yaml
charts/longhorn/templates/storageclass.yaml
charts/longhorn/templates/uninstall-job.yaml
charts/longhorn/values.yaml

Release 1.3.1 RC1

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/values.yaml

Release 1.3.1

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yml
charts/longhorn/templates/crds.yaml
charts/longhorn/templates/daemonset-sa.yaml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/templates/deployment-driver.yaml
charts/longhorn/templates/deployment-ui.yaml
charts/longhorn/templates/postupgrade-job.yaml
charts/longhorn/templates/serviceaccount.yaml
charts/longhorn/templates/storageclass.yaml
charts/longhorn/templates/uninstall-job.yaml
charts/longhorn/values.yaml

Release 1.2.5-rc1

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/values.yaml

Release 1.2.5 RC2

---

charts/longhorn/Chart.yaml
charts/longhorn/values.yaml

Release 1.2.5

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/values.yaml

Release 1.3.1 RC2

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/values.yaml

Release 1.3.2

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yml
charts/longhorn/values.yaml

Release 1.2.6

---

charts/longhorn/questions.yml

Signed-off-by: Ray Chang <ray.chang@suse.com>

fix: update version number as 1.2.6 in question.yaml

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/templates/clusterrole.yaml
charts/longhorn/templates/clusterrolebinding.yaml
charts/longhorn/templates/crds.yaml
charts/longhorn/templates/daemonset-sa.yaml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/templates/deployment-driver.yaml
charts/longhorn/templates/deployment-recovery-backend.yaml
charts/longhorn/templates/deployment-ui.yaml
charts/longhorn/templates/deployment-webhook.yaml
charts/longhorn/templates/ingress.yaml
charts/longhorn/templates/postupgrade-job.yaml
charts/longhorn/templates/serviceaccount.yaml
charts/longhorn/templates/services.yaml
charts/longhorn/templates/storageclass.yaml
charts/longhorn/templates/uninstall-job.yaml
charts/longhorn/values.yaml

build: 1.4.0-rc1

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/templates/deployment-recovery-backend.yaml
charts/longhorn/templates/deployment-ui.yaml
charts/longhorn/templates/deployment-webhook.yaml
charts/longhorn/values.yaml

build: 1.4.0-rc2

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/values.yaml

build: 1.4.0-rc3

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/values.yaml

build: 1.4.0

---

charts/longhorn/questions.yaml

fix: invalid questions.yaml

---

charts/longhorn/questions.yaml

Signed-off-by: Ray Chang <ray.chang@suse.com>
ref.
https://github.com/rancher/charts/pull/2304
https://github.com/rancher/charts/pull/2305

fix: add `Support Bundle Kit` image related variables in `questions.yaml`

---

charts/longhorn/Chart.yaml
charts/longhorn/README.md
charts/longhorn/questions.yaml
charts/longhorn/templates/crds.yaml
charts/longhorn/templates/validate-psp-install.yaml
charts/longhorn/values.yaml

release: 1.4.1-rc1

---

charts/longhorn/questions.yaml
charts/longhorn/templates/storageclass.yaml
charts/longhorn/values.yaml

Hi, I would like to add possibility to configure ReplicaAutoBalance parameter for StorageClass definition.
Signed-off-by: Tomáš Novák <tomas.novak@bcas.cz>

Add ReplicaAutoBalance param for StorageClass

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/values.yaml

release: v1.4.4-rc1

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/values.yaml

release: v1.4.4-rc2

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/values.yaml

release: v1.4.4

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/templates/preupgrade-job.yaml
charts/longhorn/values.yaml

release: v1.5.2-rc1

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/values.yaml

release: v1.5.2

---

charts/longhorn/Chart.yaml
charts/longhorn/README.md
charts/longhorn/questions.yaml
charts/longhorn/templates/_helpers.tpl
charts/longhorn/templates/clusterrole.yaml
charts/longhorn/templates/clusterrolebinding.yaml
charts/longhorn/templates/crds.yaml
charts/longhorn/templates/daemonset-sa.yaml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/templates/deployment-driver.yaml
charts/longhorn/templates/deployment-ui.yaml
charts/longhorn/templates/network-policies/backing-image-data-source-network-policy.yaml
charts/longhorn/templates/network-policies/backing-image-manager-network-policy.yaml
charts/longhorn/templates/network-policies/instance-manager-networking.yaml
charts/longhorn/templates/network-policies/manager-network-policy.yaml
charts/longhorn/templates/network-policies/recovery-backend-network-policy.yaml
charts/longhorn/templates/network-policies/ui-frontend-network-policy.yaml
charts/longhorn/templates/network-policies/webhook-network-policy.yaml
charts/longhorn/templates/preupgrade-job.yaml
charts/longhorn/templates/serviceaccount.yaml
charts/longhorn/templates/storageclass.yaml
charts/longhorn/values.yaml

release: v1.6.0-rc1

---

charts/longhorn/Chart.yaml
charts/longhorn/README.md
charts/longhorn/questions.yaml
charts/longhorn/templates/crds.yaml
charts/longhorn/templates/ingress.yaml
charts/longhorn/values.yaml

release: v1.6.0-rc2

---

charts/longhorn/Chart.yaml
charts/longhorn/README.md
charts/longhorn/questions.yaml
charts/longhorn/templates/_helpers.tpl
charts/longhorn/templates/daemonset-sa.yaml
charts/longhorn/templates/services.yaml
charts/longhorn/values.yaml

release: v1.6.0-rc3

---

charts/longhorn/Chart.yaml
charts/longhorn/questions.yaml
charts/longhorn/values.yaml

release: v1.6.0

---

charts/longhorn/Chart.yaml
charts/longhorn/README.md
charts/longhorn/questions.yaml
charts/longhorn/templates/crds.yaml
charts/longhorn/templates/daemonset-sa.yaml
charts/longhorn/templates/default-setting.yaml
charts/longhorn/templates/services.yaml
charts/longhorn/templates/storageclass.yaml
charts/longhorn/values.yaml

release: v1.5.4-rc1
